### ISSUE TITLE
Helm chart does not deploy CRD

### ISSUE THREAD

**Issue by ChipWolf** [stakater/Forecastle#105]
The helm chart does not deploy the custom resource definition.

**Comment by hmklabs-dclow** [comment]
Looks like this is happening because of changes in Helm 3

https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

tldr: remove the crd annotation `"helm.sh/hook": crd-install` and it will deploy.

**Comment by ahmedwaleedmalik** [comment]
This issue was fixed in #115
