### ISSUE TITLE
Error message on web page but nothing in logs

### ISSUE THREAD

**Issue by Nuru** [stakater/Forecastle#124]
Using stakater/forecastle:v1.0.54 docker image, the web page displays with header and footer, but the main panel just says:

```text
Results couldn't be loaded due to an error
```

- There is nothing in the server logs to indicate an error. 
- There is nothing in the web browser console.
- Viewing all requests in the browser development tools shows all requests returned with status 200.

This makes it very hard to debug.

My guess is that it is not finding any apps and is failing to display an empty list.

**Comment by usamaahmadkhan** [comment]
@Nuru plz refer to #125 . Can you see error in the logs mentioned there?

**Comment by Nuru** [comment]
> @Nuru plz refer to #125 . Can you see error in the logs mentioned there?
When I said "There is nothing in the server logs to indicate an error" I was referring to the log output from the Pod. So no, there is no error in the logs mentioned there.

**Comment by rasheedamir** [comment]
fixed
