### ISSUE TITLE
Need to include RBAC permissions for networking.k8s.io API

### ISSUE THREAD

**Issue by Nuru** [stakater/Forecastle#128]
Ingress apiVersion `extensions/v1beta1` [is deprecated and being replaced](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) with `networking.k8s.io/v1beta1`, which itself is now [deprecated and being replaced with](https://github.com/kubernetes/kubernetes/issues/90077#issuecomment-718778960) `networking.k8s.io/v1`. Forecastle needs to support the new apiVersion by both monitoring for it and enabling access to monitor for it by adding `networking.k8s.io` to the RBAC API list: https://github.com/stakater/Forecastle/blob/582efcadab987b5e6dc196a3a03cf7ab9d81cfe1/deployments/kubernetes/chart/forecastle/templates/rbac.yaml#L21

**Comment by rasheedamir** [comment]
Thanks @Nuru can you please make a PR for this change? Also add in the ReadMe about this change

**Comment by Nuru** [comment]
@rasheedamir Turns out there is a lot more to it than just adding the RBAC permission. The current code only works with the `extensions/v1beta1` API and references it explicitly. Converting it to support multiple versions of Ingress looks like a pretty big undertaking. I think you absolutely need to do it, because it is hard to switch an entire cluster over from one Ingress API to another all at once, but I'm not sure I'm up for volunteering that much time on this project.

**Comment by Nuru** [comment]
@rasheedamir do you have plans to support `networking.k8s.io/v1beta1` and `networking.k8s.io/v1` Ingresses, either by supporting all 3 versions at once or by releasing multiple versions of Forecastle, one for each version of Ingress?

**Comment by aslafy-z** [comment]
Can I take the task?
Are we ok to drop support for extensions Ingresses?

**Comment by rasheedamir** [comment]
sure @aslafy-z we welcome PRs
