### ISSUE TITLE
v1.0.62 broken

### ISSUE THREAD

**Issue by REBELinBLUE** [stakater/Forecastle#147]
I have been running v1.0.62 fine for weeks, this morning when my pod restarted I started getting just 404 responses from the application. Looking at docker hub it appears someone pushed a new image to v1.0.62 yesterday so I think someone has pushed something which is broken?

Switching back to v1.0.61 or forward to v1.0.63 and it works fine again

**Comment by usamaahmadkhan** [comment]
@REBELinBLUE plz upgrade to v1.0.63. We shifted to github workflows and v1.0.62 was re-pushed (image was broken) Inconvenience is regretted. 
Closing this. Feel free to re-open if face issues again.

**Comment by REBELinBLUE** [comment]
That is what I did, just thought I should report the issue as you probably didn't mean to break an existing image ;)
