### ISSUE TITLE
1.0.65?

### ISSUE THREAD

**Issue by davidkarlsen** [stakater/Forecastle#149]
I'm seeing this chart version:
```
helm search repo forecastle
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                             
stakater/forecastle     1.0.65                          forecastle chart that runs on kubernetes
```
but only 1.0.63 in this repo.
Where does it come from?

**Comment by madddi** [comment]
```
NAME               	CHART VERSION	APP VERSION	DESCRIPTION                             
stakater/forecastle	1.0.65       	           	forecastle chart that runs on kubernetes
stakater/forecastle	v1.0.64      	           	forecastle chart that runs on kubernetes
stakater/forecastle	v1.0.63      	           	forecastle chart that runs on kubernetes
```

This also breaks some automatic version checks as the version number is not prefixed.

**Comment by rasheedamir** [comment]
@ahmedwaleedmalik please take a look

**Comment by davidkarlsen** [comment]
Try running stakater/forecastle:v1.0.65 - it will spit out random binary garbage and can't be tracked back to a release, so it looks suspicious like a supply chain attack.

**Comment by usamaahmadkhan** [comment]
That was because the pipeline got messed up previously and it wrongly missed the frontend wrapper and pushed the image. I have removed that chart from repository. v1.0.64 is the latest usable chart.

**Comment by davidkarlsen** [comment]
Maybe the image should be removed too as it is not working and looks suspect

**Comment by usamaahmadkhan** [comment]
Removed the image as well. you might have it locally. Closing. Feel free to open if needed.
