### ISSUE TITLE
Add support for changing the page title

### ISSUE THREAD

**Issue by servo1x** [stakater/Forecastle#172]
Since the page header is configurable, the page title should be configurable as well.

**Comment by faizanahmad055** [comment]
@servo1x Can you please elaborate the requirement

**Comment by servo1x** [comment]
Hi @faizanahmad055 - we should be able to set the page title: https://github.com/stakater/Forecastle/blob/c21fd90367d60c368e5b9ef12431fe0d4b5eea3b/frontend/public/index.html#L12

**Comment by pnowy** [comment]
👍 , that would be nice to have that kind of parametrization (this forecastle title could be added to footer next to Stakater).

**Comment by rgarrigue** [comment]
I actually expected (Helm chart) `forecastle.config.title` to set the page title instead of a header in the page. Wouldn't mind the param setting both.
