### ISSUE TITLE
Migrating from ingress networking.k8s.io/v1beta1 to /v1 

### ISSUE THREAD

**Issue by runningman84** [stakater/Forecastle#183]
Please update your chart, right now it is not working with k8s 1.22 or newer:

https://blog.hycorve.com/migrating-from-ingress-networking-k8s-io-v1beta1-to-v1/

**Comment by runningman84** [comment]
just take a look at this pr:
https://github.com/stakater/Forecastle/pull/174

**Comment by davidkarlsen** [comment]
Any news? Install fails with:
```
beginning wait for 1 resources with timeout of 1m0s
  Normal  info   6m59s (x2 over 10m)  helm-controller  Helm install has started
  Normal  error  6m52s (x2 over 10m)  helm-controller  reconciliation failed: Helm install failed: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
  Normal  error  6m52s                helm-controller  Helm install failed: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
```

**Comment by rasheedamir** [comment]
we just fixed the pipeline; @davidkarlsen and @runningman84 can you plz test again?

**Comment by davidkarlsen** [comment]
@rasheedamir it seems it was actually released. so I don't think we can re-run it.

**Comment by aslafy-z** [comment]
I've seen that `ingressClassName` field is missing in the Ingress Spec. It should not be a blocker but still, this field needs to be added.

**Comment by davidkarlsen** [comment]
> I've seen that `ingressClassName` field is missing in the Ingress Spec. It should not be a blocker but still, this field needs to be added.

fancy doing a pull-request for it?

**Comment by faizanahmad055** [comment]
@davidkarlsen Can you please review this: #188

**Comment by aslafy-z** [comment]
@faizanahmad055 Awesome, I was about to open a PR but you did it before me :+1: 
I guess this issue can now be closed.

**Comment by faizanahmad055** [comment]
#188 and #174 fixes this
