### ISSUE TITLE
Results couldn't be loaded due to an error

### ISSUE THREAD

**Issue by michas2** [stakater/Forecastle#202]
I installed forecastle using `helm install forecastle stakater/forecastle`.

When I access the web interface I only get "Results couldn't be loaded due to an error".
There is no error shown in `kubectl logs`.

What might be wrong? Is there a way to debug further?

**Comment by michas2** [comment]
From what I see, the `api/apps` endpoint simply return `null`.
Looks like the `AppsHandler` in the backend is unhappy, but for some reason does not log any error message.
I'm not sure how to debug this any further without major effort.

**Comment by muammercakir** [comment]
I have the same issue with the latest helm chart version 1.0.97.

**Comment by igorcoding** [comment]
I'm stuck with the same issue. Is there any solution to this?

**Comment by Xide** [comment]
I encountered the same issue after a fresh Forecastle install. 
The issue for me was that had not configured any ingress with a `forecastle.stakater.com/expose` annotation yet. 
After adding this annotation to an ingress, the error message was gone.

**Comment by rasheedamir** [comment]
@davidkarlsen can you please check this issue as well?

**Comment by davidkarlsen** [comment]
I can have a look, can you add some stack-traces please?

**Comment by karl-johan-grahn** [comment]
@michas2 can you add stack-traces please?

**Comment by andrasnemethcg** [comment]
In a fresh installation of [forecastle (1.0.131)](forecastle:v1.0.131), we same error as above. The api/apps returns null. 

The crd is installed and I tried both annotating an existing ingress and creating an Kind:ForecastleApp. Namespace selector is any.
There is no error in the pod log. How can I debug further where is the error? 
```
time="2023-10-26T11:09:06Z" level=info msg="Looking for forecastle apps in the following namespaces: * (All Namespaces)" _source="handlers/appsHandler.go:51"
```

**Comment by andrasnemethcg** [comment]
> In a fresh installation of forecastle (1.0.131), we same error as above. The api/apps returns null.
> 
> The crd is installed and I tried both annotating an existing ingress and creating an Kind:ForecastleApp. Namespace selector is any. There is no error in the pod log. How can I debug further where is the error?
> 
> ```
> time="2023-10-26T11:09:06Z" level=info msg="Looking for forecastle apps in the following namespaces: * (All Namespaces)" _source="handlers/appsHandler.go:51"
> ```

After some digging around, it seems that instanceName filtered out my applications. So, now it is set to empty and works.

**Comment by MuneebAijaz** [comment]
@andrasnemethcg , @michas2 can we close this issue if its fixed on your side? or do we need some code change?

**Comment by andrasnemethcg** [comment]
> @andrasnemethcg , @michas2 can we close this issue if its fixed on your side? or do we need some code change?

My problem was solved by removing instanceName. Ok to close from my point of view. However, this is not my issue, but @michas2 's.
