### ISSUE TITLE
Deploy and remove from the launchpad

### ISSUE THREAD

**Issue by slamer59** [stakater/Forecastle#292]
Hello,
sometime we don't need an application to run all day long but just to launch it from time to time and remove if from kubernetes. 

I wonder if we can implement a function that keep definition of an application and deploy it when needed. And destroy it when log off ?

Regards

**Comment by rasheedamir** [comment]
@slamer59 when the application is removed the forecastle app should be removed as well; that's how we do

**Comment by slamer59** [comment]
> @slamer59 when the application is removed the forecastle app should be removed as well; that's how we do
So it doesnot hold parameters to redeploy later.
Thanks for this feedback.
