### ISSUE TITLE
[ENHANCE]: Add helm repo to documentation

### ISSUE THREAD

**Issue by andrasnemethcg** [stakater/Forecastle#398]
There was a request to add "add a proper helm repository" #141 , which was closed that "It is already in stakater-charts. Closing".
Can we have this also in the [documentation](https://github.com/stakater/Forecastle/tree/master#helm-charts)?
`helm repo add stakater-charts https://stakater.github.io/stakater-charts/`

**Comment by karl-johan-grahn** [comment]
You can create a PR if you'd like to add this
