### ISSUE TITLE
[BUG] the chart creates a duplicate security context under certain conditions

### ISSUE THREAD

**Issue by wy100101** [stakater/Forecastle#428]
**Describe the bug**
the forecastle chart creates a duplicate security context when you set .Values.forecastle.deployment.securityContext resulting in an invalid manifest.

**To Reproduce**
helm deploy forecastle with securityContext set under .Values.forecastle.deployment.securityContext will result in the following error:
Helm install failed for release forecastle/forecastle with chart forecastle@v1.0.142: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 46: mapping key "securityContext" already defined at line 35

**Expected behavior**
A clean helm install

**Screenshots**

**Environment**
 - Operator Version:
 - Kubernetes/OpenShift Version: EKS

**Additional context**

**Comment by bnallapeta** [comment]
@wy100101 Ack. Will work on it.

**Comment by karl-johan-grahn** [comment]
The issue can be reproduced with `helm template`.

Unit test could be added with `d3adb5/helm-unittest-action`. Example tests: https://github.com/d3adb5/helm-unittest-action/blob/master/example-chart/tests/example_test.yaml
