### ISSUE TITLE
Add access level mark on discovered services

### ISSUE THREAD

**Issue by usamaahmadkhan** [stakater/Forecastle#66]
Some of the services are restricted on the corporate network for security purposes e.g. services that expose cluster info/data. There should be some kind of indication (widget) which could indicate that this service is network restricted so that the users are more aware about these services.

**Comment by waseem-h** [comment]
Do you have any idea on how would you approach this? Can we somehow look for NetworkPolicy or PodSecurityPolicy and add the indication based on that? Or should we just have a simple annotation that needs to be explicitly set by the user to indicate that this is a network restricted service?

**Comment by usamaahmadkhan** [comment]
How about adding a default check for nginx-ingress annotation. external-ingress means it is public and internal means it is network restricted.

**Comment by waseem-h** [comment]
I believe that is just our usecase that we have 2 different nginx ingress controllers with specific names `internal-ingress` and `external-ingress`. Implementing it like you mentioned would restrict users to use this feature in many ways. Lets say they don't even run an nginx controller and they don't have annotations specified for their controller. I think we need to approach this in a more generic and decoupled way in which our scenario can also easily fit

**Comment by usamaahmadkhan** [comment]
Then NetworkPolicy should do it. We should assign labels like `network-restricted=true/false` to pod that require restriction and then use `PodSelector` in NetworkPolicy to restrict those pods. Similarly watching this annotation when adding a mark on the UI.

**Comment by waseem-h** [comment]
@usamaahmadkhan I think we should start from the basic, i.e., allow users to specify whether an app is network restricted or not manually. And then support automatic detection. Partial support is already in for this in #78 . We can use the annotation `forecastle.stakater.com/network-restricted` to specify if an app is restricted or not

**Comment by waseem-h** [comment]
The feature has been implemented in #80
