### ISSUE TITLE
Ability to specify app root path

### ISSUE THREAD

**Issue by waseem-h** [stakater/Forecastle#67]
As explained by @Nuru in another ticket:
I would also like to have the ability to explicitly specify the linked path via an annotation. It is an issue right now in that I have an app where I want the Forecastle icon to take the user to https://host/console/view but it only goes to https://host/

This is somewhat similar to, but different than, the nginx-ingress annotation nginx.ingress.kubernetes.io/app-root. In this case, I do not want to generally redirect /, I just want to specify the path for the Forecastle link.

**Comment by Nuru** [comment]
Thanks, @waseem-h.  I don't actually want to set the "app root" path, I just want to specify the target of the Forecastle link. I want to keep the "app root" `/` which is why the `nginx` annotation is not sufficient.

**Comment by waseem-h** [comment]
I'm a bit confused now @Nuru. What exactly do you need here? For example you have an ingress that points to example.com, what do you need to append to this ingress URL and have it as a link in forecastle? From my understanding, I thought you wanted to append something like `/admin` to the URL when showing in forecastle. If it's just appending then we can choose not to name it app-root since it's not actually an app root its just a subpath that you want to use in forecastle but want the root url same in ingress. If its something else then please let me know here

**Comment by Nuru** [comment]
@waseem-h As I explained initially
> I  have an app where I want the Forecastle icon to take the user to https://host/console/view but it only goes to https://host/

I have since had the use case where Forecastle's link is http://host/ but I want it to be https://host/ and I had to create a fake `tls` entry in the ingress to accomplish that. I would much rather have an annotation that says something like `forecastle/link: https://host/console/view`.

I don't want to set `app-root` because I want `https://host/` to still be available when accessed from elsewhere.

**Comment by rasheedamir** [comment]
very good suggestion @Nuru; please create separate ticket for it

**Comment by waseem-h** [comment]
@Nuru makes sense now. I will update the PR with the change and will let you know once it is released
