### ISSUE TITLE
Feature request: Add arbitrary links 

### ISSUE THREAD

**Issue by Nuru** [stakater/Forecastle#70]
Feature Request:

It would be nice if I could just explicitly add an external link (for example to PagerDuty) to a Forescatle ingress group without requiring an ingress. Forecastle puts together a nice collection of all the dynamic ingresses, but I would like to include links to external resources on the same page

**Comment by rasheedamir** [comment]
https://github.com/stakater/Forecastle/pull/71

PR in progress!
