### ISSUE TITLE
Feature Request: Display additional app info as tool tip 

### ISSUE THREAD

**Issue by marascha** [stakater/Forecastle#74]
We use Forecastle and really like it. I'm trying to convince other teams in our company to use it as well. It would be great to be able to display additional information on a registered app e.g. in a tool tip or something alike.

**what**
Display additional information for a registered app such as links to monitoring and tracing tools, maintainer, SLAs, image version and so on. This information could be displayed as tool tip or in an info panel.

**why**
Display all relevant info and links for an app in a central place (Single point of truth for all apps in a k8 cluster).

**how**
Additional info can be registered as a simple key/value list or an html snippet by the app. Forecastle then displays the provided data as a table in a tool tip or info panel. URLs are recognized based on regular expressions and automatically displayed as links.

**Comment by rasheedamir** [comment]
Great suggestion @marascha 

Would you like to create a PR? We can definitely help you get going; if you are a newbie to Go lang.

**Comment by marascha** [comment]
@rasheedamir I would love to.I can only do it in my leisure time and right now, I'm quite busy with other stuff. I might be able to do it sometime later like in couple of weeks...

**Comment by rasheedamir** [comment]
@marascha me and @waseem-h had a discussion today and we have a plan how to implement it; and @waseem-h is going to lead the development

**Comment by rasheedamir** [comment]
@marascha our initial thoughts to have new UI wireframes

![forecastle](https://user-images.githubusercontent.com/3967672/66712348-c017a680-ed9b-11e9-8b1a-049dcdb6c87c.png)

**Comment by marascha** [comment]
@rasheedamir It looks perfect to me, thanks!
Key-Value Pairs in details section having an URL as value are automatically recognized as clickable links, right?

I've one more suggestion which might be interesting to you as well. The ingress could expose a comma-seperated list called autoextract or alike including the jsonpaths of specific pod values which are desired to be auto-extracted and displayed in the details list. I think an example could make this more clear:

`Name:         app-ingress                                                                                                                        ...
│Annotations:  forecastle.stakater.com/appName: myapp                                                                                                                                                        ││              forecastle.stakater.com/expose: true                                                                                                                                                                                                                                                                                                                   ││              forecastle.stakater.com/autoextract: {$.spec.template.spec.containers[:1].image}, {$.spec.template.spec.containers[:1].name}
 ` 

Details section:
image: 'myapp:latest'
name: 'myapp'

The syntax of jsonpath might be incorrect. But I think the idea is clear...

**Comment by rasheedamir** [comment]
interesting thought @marascha actually we have been thinking for a while to create a separate tool which is just a visualizer of k8s manifests

but yeah this could be implemented in forecastle; @waseem-h what do you think?

**Comment by waseem-h** [comment]
@rasheedamir Yeah we can definitely implement it in forecastle. But let's focus on getting the details as plain text via annotations first and once that is in place, we can add support for jsonPath or similar. @marascha Also I would encourage you to use CRDs which is our upcoming feature releasing with #77 as it will allow you to separate forcastle app config from the ingress object and instead of specifying complex data inside annotations, you could just add them in yaml format which is much convenient to look at and maintain

**Comment by marascha** [comment]
@waseem-h awesome. Having specific CRDs for forecastle configurations is a great idea. We'll definitely use them.

**Comment by waseem-h** [comment]
@marascha you can use `v1.0.30` which has CRD support. Although it is a bit limited right now since you have to specify the URL's explicitly in the CRD. We will soon support fieldSelectors or something similar which will allow you to specify where to find the URL from. Something like:

```yaml
spec:
  urlFrom:
    ingress:
      name: my-ingress-object
      namespace: ns
```

**Comment by waseem-h** [comment]
With `v1.0.32` we also have support for discovering ingress URLs using CRDs. You can use that like so:
```yaml
spec:
  urlFrom:
    ingressRef:
      name: my-ingress-object
```
in the `ForecastleApp` CR

@marascha

**Comment by marascha** [comment]
@waseem-h Thank you very much. I'll give it a shot soon.

**Comment by waseem-h** [comment]
@marascha We now have support for app properties / details. You can use this version: https://github.com/stakater/Forecastle/releases/tag/v1.0.34

**Comment by marascha** [comment]
@waseem-h Thank you very much guys. You are awesome!
