### ISSUE TITLE
Inadequate defaults in values.yaml

### ISSUE THREAD

**Issue by toxuin** [stakater/Forecastle#85]
- Upon deployment with helm `deployment` and `service` receive irrelevant annotations with what seems to be some values internal to stakater org:

deployment:
`authproxy.stakater.com/redirection-url: https://cp.stackator.com`
service:
`config.xposer.stakater.com/Domain: "stackator.com"`
etc.

There is no other way to override those values than to edit `values.yaml` - therefore this chart cannot be packed and hosted (in ChartMuseum for example).

- There is no ingress created with deployment through helm. Seems like ingress creation is handled by another tool - xposer, that is neither a dependency of forecastle nor even mentioned on the `README.md`. Maybe add a config option to choose one or another?

- `README.md` has outdated configuration parameter names. See `crdEnabled` vs [`values.yaml: createCustomResource `](https://github.com/stakater/Forecastle/blob/c4a8eba850cee12b2c161d290c5170ce5f1171e4/deployments/kubernetes/chart/forecastle/values.yaml#L2).

- `README.md` also does not mention that all config values have to be prepended with `forecastle.`, therefore `helm ... --set title="My Title"` has no effect and has to be transformed to `helm ... --set forecastle.config.title="My Title"`.

**Comment by waseem-h** [comment]
Hi @toxuin . Thanks for pointing out the inconsistencies in the readme. I will try to fix them in the coming week

**Comment by waseem-h** [comment]
Regarding the annotations, they need to be removed as they are not needed. I will fix it as well

**Comment by davidkarlsen** [comment]
Any news here? Could you also add an ingress to the chart?

**Comment by rasheedamir** [comment]
tjena @davidkarlsen @waseem-h will look into soon and get it merged
